// <auto-generated />
using JustShop.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JustShop.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JustShop.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Laptops",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eleifend dui nunc, vel aliquet diam viverra vel. ",
                            ImageUrl = "https://vitaliikutsan.blob.core.windows.net/justshop/Images/macbook.jpg",
                            Name = "MacBook",
                            Price = 1500.0
                        },
                        new
                        {
                            Id = 2,
                            Category = "Laptops",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eleifend dui nunc, vel aliquet diam viverra vel. ",
                            ImageUrl = "https://vitaliikutsan.blob.core.windows.net/justshop/Images/hp.png",
                            Name = "HP Laptop",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 3,
                            Category = "Phones",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eleifend dui nunc, vel aliquet diam viverra vel. ",
                            ImageUrl = "https://vitaliikutsan.blob.core.windows.net/justshop/Images/iphone-12.jpg",
                            Name = "Iphone 12",
                            Price = 700.0
                        },
                        new
                        {
                            Id = 4,
                            Category = "Phones",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eleifend dui nunc, vel aliquet diam viverra vel. ",
                            ImageUrl = "https://vitaliikutsan.blob.core.windows.net/justshop/Images/iphone-13.png",
                            Name = "Iphone 13",
                            Price = 900.0
                        },
                        new
                        {
                            Id = 5,
                            Category = "Watches",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eleifend dui nunc, vel aliquet diam viverra vel. ",
                            ImageUrl = "https://vitaliikutsan.blob.core.windows.net/justshop/Images/watch.jpeg",
                            Name = "Apple watch",
                            Price = 500.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
